-- COMP 440 Course Project - Phases 1 and 2
-- Fresh-install schema for the electronics marketplace.
--
-- Run this file when setting up a brand-new local database. Teammates who
-- already have Phase 1 users should run migration.sql instead so their existing
-- accounts are preserved. Keep both SQL files synchronized when the data model
-- changes, but do not add DROP TABLE statements here unless a full reset is
-- intentionally required.

-- CREATE DATABASE IF NOT EXISTS makes first-time setup and accidental reruns
-- safe. The application expects this name unless COMP440_DB_NAME is overridden.
CREATE DATABASE IF NOT EXISTS comp440_p1;
USE comp440_p1;

-- ---------------------------------------------------------------------------
-- Registered users and authentication data
-- ---------------------------------------------------------------------------
-- username is the stable identifier referenced by marketplace tables. Email
-- and phone are independently unique so one person cannot register duplicates.
-- password stores a Werkzeug hash, never a plaintext password.
CREATE TABLE IF NOT EXISTS user (
    username   VARCHAR(50)  NOT NULL,
    password   VARCHAR(255) NOT NULL,
    firstName  VARCHAR(50)  NOT NULL,
    lastName   VARCHAR(50)  NOT NULL,
    email      VARCHAR(100) NOT NULL,
    phone      VARCHAR(20)  NOT NULL,
    PRIMARY KEY (username),
    UNIQUE KEY uq_user_email (email),
    UNIQUE KEY uq_user_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Marketplace listings
-- ---------------------------------------------------------------------------
-- itemId is generated by MySQL and is the public listing identifier. Status
-- lets the application hide sold/removed listings from the feed while keeping
-- purchase history available to the seller.
CREATE TABLE IF NOT EXISTS item (
    itemId       INT           NOT NULL AUTO_INCREMENT,
    title        VARCHAR(120)  NOT NULL,
    description TEXT          NOT NULL,
    datePosted   DATE          NOT NULL,
    price        DECIMAL(10,2) NOT NULL,
    seller       VARCHAR(50)   NOT NULL,
    status       ENUM('active', 'sold', 'removed') NOT NULL DEFAULT 'active',
    PRIMARY KEY (itemId),
    -- These indexes support seller history, daily-limit checks, and date sorts.
    KEY idx_item_seller_date (seller, datePosted),
    KEY idx_item_date (datePosted),
    CONSTRAINT fk_item_seller FOREIGN KEY (seller) REFERENCES user(username),
    CONSTRAINT chk_item_price CHECK (price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Categories and item/category relationships
-- ---------------------------------------------------------------------------
-- Categories are shared values rather than repeated text on each listing. The
-- CHECK constraint enforces the assignment's lowercase single-word format.
CREATE TABLE IF NOT EXISTS category (
    categoryName VARCHAR(50) NOT NULL,
    PRIMARY KEY (categoryName),
    CONSTRAINT chk_category_lowercase_word
        CHECK (categoryName REGEXP '^[a-z]+$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Audit rows remain after an item is deleted so deleting a listing cannot be
-- used to bypass the two-posts-per-day rule.
-- There is intentionally no foreign key back to item: deleting the item must
-- not delete the evidence that the user already posted it that day.
CREATE TABLE IF NOT EXISTS item_post_history (
    itemId     INT         NOT NULL,
    seller     VARCHAR(50) NOT NULL,
    datePosted DATE        NOT NULL,
    PRIMARY KEY (itemId),
    KEY idx_post_history_user_date (seller, datePosted),
    CONSTRAINT fk_post_history_user FOREIGN KEY (seller) REFERENCES user(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- An item can have many categories and a category can contain many items. The
-- composite primary key prevents assigning the same category twice. Cascades
-- clean up only relationship rows when an item/category is removed.
CREATE TABLE IF NOT EXISTS item_category (
    itemId       INT         NOT NULL,
    categoryName VARCHAR(50) NOT NULL,
    PRIMARY KEY (itemId, categoryName),
    KEY idx_item_category_name (categoryName, itemId),
    CONSTRAINT fk_item_category_item FOREIGN KEY (itemId)
        REFERENCES item(itemId) ON DELETE CASCADE,
    CONSTRAINT fk_item_category_category FOREIGN KEY (categoryName)
        REFERENCES category(categoryName) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Reviews and community interactions
-- ---------------------------------------------------------------------------
-- Ratings use the four exact assignment values. The reviewer/item unique key
-- is the database-level one-review-per-item rule; the trigger below handles the
-- self-review and daily-count rules that require looking at other rows.
CREATE TABLE IF NOT EXISTS review (
    reviewId   INT          NOT NULL AUTO_INCREMENT,
    itemId     INT          NOT NULL,
    reviewer   VARCHAR(50)  NOT NULL,
    rating     ENUM('Poor', 'Fair', 'Good', 'Excellent') NOT NULL,
    comment    VARCHAR(500) NOT NULL,
    reviewDate DATE         NOT NULL,
    PRIMARY KEY (reviewId),
    UNIQUE KEY uq_review_reviewer_item (reviewer, itemId),
    KEY idx_review_item (itemId),
    KEY idx_review_reviewer_date (reviewer, reviewDate),
    CONSTRAINT fk_review_item FOREIGN KEY (itemId)
        REFERENCES item(itemId) ON DELETE CASCADE,
    CONSTRAINT fk_review_reviewer FOREIGN KEY (reviewer)
        REFERENCES user(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- A composite primary key gives each user at most one like per item while still
-- allowing unlimited likes across different items. Likes cascade with items.
CREATE TABLE IF NOT EXISTS item_like (
    itemId   INT         NOT NULL,
    username VARCHAR(50) NOT NULL,
    likedAt  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (itemId, username),
    CONSTRAINT fk_like_item FOREIGN KEY (itemId)
        REFERENCES item(itemId) ON DELETE CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY (username)
        REFERENCES user(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- This audit table keeps the daily submission count even when an item's
-- reviews are removed by an item deletion cascade.
-- As with item_post_history, no review foreign key is intentional: the audit
-- count must outlive the review row it records.
CREATE TABLE IF NOT EXISTS review_submission_history (
    reviewId   INT         NOT NULL,
    reviewer   VARCHAR(50) NOT NULL,
    reviewDate DATE        NOT NULL,
    PRIMARY KEY (reviewId),
    KEY idx_review_history_user_date (reviewer, reviewDate),
    CONSTRAINT fk_review_history_user FOREIGN KEY (reviewer) REFERENCES user(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Purchases
-- ---------------------------------------------------------------------------
-- Each listing represents one sellable unit, so UNIQUE(itemId) permits only one
-- completed purchase. pricePaid records the checkout value permanently rather
-- than depending on the listing's later state. Purchase foreign keys do not
-- cascade because transaction history should not disappear with a listing.
CREATE TABLE IF NOT EXISTS purchase (
    purchaseId  INT           NOT NULL AUTO_INCREMENT,
    itemId      INT           NOT NULL,
    buyer       VARCHAR(50)   NOT NULL,
    seller      VARCHAR(50)   NOT NULL,
    pricePaid   DECIMAL(10,2) NOT NULL,
    purchaseDate DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (purchaseId),
    UNIQUE KEY uq_purchase_item (itemId),
    KEY idx_purchase_buyer (buyer),
    CONSTRAINT fk_purchase_item FOREIGN KEY (itemId) REFERENCES item(itemId),
    CONSTRAINT fk_purchase_buyer FOREIGN KEY (buyer) REFERENCES user(username),
    CONSTRAINT fk_purchase_seller FOREIGN KEY (seller) REFERENCES user(username),
    CONSTRAINT chk_purchase_distinct_users CHECK (buyer <> seller),
    CONSTRAINT chk_purchase_price CHECK (pricePaid >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Database-enforced business rules
-- ---------------------------------------------------------------------------
-- MySQL does not provide CREATE OR REPLACE TRIGGER. Dropping only our known
-- trigger names makes this file rerunnable and ensures their definitions match
-- the current project code.
DROP TRIGGER IF EXISTS trg_item_daily_limit;
DROP TRIGGER IF EXISTS trg_item_post_history;
DROP TRIGGER IF EXISTS trg_review_rules;
DROP TRIGGER IF EXISTS trg_review_submission_history;
DROP TRIGGER IF EXISTS trg_review_no_update;
DROP TRIGGER IF EXISTS trg_review_no_delete;
DROP TRIGGER IF EXISTS trg_purchase_rules;

-- Trigger bodies contain their own semicolons, so Workbench needs a temporary
-- delimiter until all BEGIN/END blocks have been defined.
DELIMITER $$

-- Force the authoritative posting date to the database server's current date,
-- then reject a third item. The audit table prevents deletion from resetting
-- this count.
CREATE TRIGGER trg_item_daily_limit
BEFORE INSERT ON item
FOR EACH ROW
BEGIN
    SET NEW.datePosted = CURRENT_DATE();
    IF (SELECT COUNT(*) FROM item_post_history
        WHERE seller = NEW.seller AND datePosted = NEW.datePosted) >= 2 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'A user may post at most two items per calendar day.';
    END IF;
END$$

-- Record every successful item insertion in the same transaction. A rollback
-- of the item also rolls back its audit row.
CREATE TRIGGER trg_item_post_history
AFTER INSERT ON item
FOR EACH ROW
BEGIN
    INSERT INTO item_post_history (itemId, seller, datePosted)
    VALUES (NEW.itemId, NEW.seller, NEW.datePosted);
END$$

-- Force the authoritative review date, reject reviews of a seller's own item,
-- and enforce the three-reviews-per-day maximum. UNIQUE(reviewer, itemId) on the
-- review table separately enforces one review per user/item pair.
CREATE TRIGGER trg_review_rules
BEFORE INSERT ON review
FOR EACH ROW
BEGIN
    SET NEW.reviewDate = CURRENT_DATE();
    IF EXISTS (SELECT 1 FROM item
               WHERE itemId = NEW.itemId AND seller = NEW.reviewer) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'A user cannot review their own item.';
    END IF;

    IF (SELECT COUNT(*) FROM review_submission_history
        WHERE reviewer = NEW.reviewer AND reviewDate = NEW.reviewDate) >= 3 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'A user may submit at most three reviews per calendar day.';
    END IF;
END$$

-- Add to permanent daily history only after the review passes every BEFORE
-- trigger and table constraint.
CREATE TRIGGER trg_review_submission_history
AFTER INSERT ON review
FOR EACH ROW
BEGIN
    INSERT INTO review_submission_history (reviewId, reviewer, reviewDate)
    VALUES (NEW.reviewId, NEW.reviewer, NEW.reviewDate);
END$$

-- Reviews are immutable assignment records. Blocking updates and deletes in
-- MySQL keeps this rule true even if someone bypasses the Flask interface.
CREATE TRIGGER trg_review_no_update
BEFORE UPDATE ON review
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Reviews cannot be modified after submission.';
END$$

CREATE TRIGGER trg_review_no_delete
BEFORE DELETE ON review
FOR EACH ROW
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Reviews cannot be deleted after submission.';
END$$

-- Buyers cannot purchase their own listing, and a purchase is accepted only
-- while the listing is active. UNIQUE(purchase.itemId) is the final database
-- guarantee that a listing is sold once.
CREATE TRIGGER trg_purchase_rules
BEFORE INSERT ON purchase
FOR EACH ROW
BEGIN
    IF EXISTS (SELECT 1 FROM item
               WHERE itemId = NEW.itemId AND seller = NEW.buyer) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'A seller cannot buy their own item.';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM item
                   WHERE itemId = NEW.itemId AND status = 'active') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'This item is no longer available.';
    END IF;
END$$

-- Return Workbench to its normal delimiter for any SQL run afterward.
DELIMITER ;
